DROP TABLE IF EXISTS compilation_event_link, compilations, participant_requests, events, categories, users;

CREATE TABLE "users"(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR(255) NOT NULL,
    "email" VARCHAR(255) NOT NULL UNIQUE,
    "del_date" TIMESTAMP WITHOUT TIME ZONE
);

CREATE TABLE "categories"(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE "events"(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" BIGINT NOT NULL REFERENCES users(id),
    "annotation" VARCHAR(2000) NOT NULL,
    "category_id" BIGINT NOT NULL REFERENCES categories(id),
    "description" VARCHAR(7000) NOT NULL,
    "event_date" TIMESTAMP WITHOUT TIME ZONE,
    "lat" FLOAT NOT NULL,
    "lon" FLOAT NOT NULL,
    "paid" BOOLEAN,
    "participant_limit" INTEGER,
    "request_moderation" BOOLEAN,
    "title" VARCHAR(120) NOT NULL,
    "status" VARCHAR(50) NOT NULL,
    "create_date" TIMESTAMP WITHOUT TIME ZONE,
    "publish_date" TIMESTAMP WITHOUT TIME ZONE
);

CREATE INDEX ix_events_users on events (user_id);
CREATE INDEX ix_events_categories on events (category_id);

CREATE TABLE "participant_requests"(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "event_id" BIGINT NOT NULL REFERENCES events(id),
    "requester_id" BIGINT NOT NULL REFERENCES users(id),
    "status" VARCHAR(50) NOT NULL,
    "created" TIMESTAMP WITHOUT TIME ZONE
);

CREATE INDEX ix_participant_requests_events on participant_requests (event_id);
CREATE INDEX ix_participant_requests_users on participant_requests (requester_id);

CREATE TABLE "compilations"(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "pinned" BOOLEAN,
    "title" VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE "compilation_event_link"(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "compilation_id" BIGINT NOT NULL REFERENCES compilations(id),
    "event_id" BIGINT NOT NULL REFERENCES events(id)
);

CREATE INDEX ix_comp_event_link_comp on compilation_event_link (compilation_id);
CREATE INDEX ix_comp_event_link_events on compilation_event_link (event_id);